### ISSUE TITLE
Tunnel url showing error 404

### ISSUE THREAD

**Issue by abskrj** [azimjohn/jprq.live#1]
The server is deployed on kubernetes.

Dockerfile ->
![Dockerfile](https://user-images.githubusercontent.com/27128838/90418812-45ae6600-e0d3-11ea-935b-776bbcf06d15.jpg)

**Comment by azimjohn** [comment]
@abhishekraj272 I think it might be a DNS issue if you're getting a 404 page not found error.
You need to add a DNS record *.example.com that direct to the same address of the application.

To be able to add a DNS record to domain names, you usually need to own the domain.
Here's an example of jprq.live DNS settings.
<img width="1191" alt="Screen Shot 2020-08-17 at 18 27 30" src="https://user-images.githubusercontent.com/35038240/90420292-0cb4c800-e0b8-11ea-9d79-d13cfb83ce6b.png">

**Comment by abskrj** [comment]
Yes, the domain is already added, there are also 5-10 services running on kubernetes and connected to same domain, and tunnel.example.com is connected to the jprq.live server.

**Comment by azimjohn** [comment]
Is there an ingress controller exposing the services?
You would also need to direct all incoming requests for *.example.com from the ingress controller.

**Comment by azimjohn** [comment]
This is the nginx configuration for jprq.live server.
```
server {
    server_name *.jprq.live;

    location = /favicon.ico { access_log off; log_not_found off; }

    location /_ws/ {
        include proxy_params;
        proxy_pass http://localhost:4200;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_connect_timeout       600;
        proxy_send_timeout          600;
        proxy_read_timeout          600;
        send_timeout                600;
    }

    location / {
        include proxy_params;
        proxy_pass http://localhost:4200;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/jprq.live/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/jprq.live/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}


server {
    server_name *.jprq.live;

    location = /favicon.ico { access_log off; log_not_found off; }

    location /_ws/ {
        include proxy_params;
        proxy_pass http://localhost:4200;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_connect_timeout       600;
        proxy_send_timeout          600;
        proxy_read_timeout          600;
        send_timeout                600;
    }

    location / {
        include proxy_params;
        proxy_pass http://localhost:4200;
    }

    listen 80;
}
```

**Comment by abskrj** [comment]
Thanks for the help man😀. The issue got resolved. Nice code though. 😉
