### ISSUE TITLE
Hanging After working for a while

### ISSUE THREAD

**Issue by user3470** [azimjohn/jprq.live#13]
This is by far the easiest but somehow after a few days of normal working the channel stops to work, what could be the issue and is it anything to do with my usage ?

It's not working at the moment

**Comment by azimjohn** [comment]
Hello, 
Sorry for replying so late, JPRQ Tunnels are meant to be used for only a few hours for testing out webhooks, bots, websites, etc. JPRQ is not meant for use for production servers. 

I am closing this issue, feel free to open it again if I didn't understand the problem correctly.
