### ISSUE TITLE
I want to know how can I increase the session timeout.

### ISSUE THREAD

**Issue by abskrj** [azimjohn/jprq.live#2]
Right now the tunnel session ends in approx half hour, is there any way to increase it to 24hrs?

**Comment by azimjohn** [comment]
The timeout was probably due to the Nginx configuration.
Updated them to timeout in 1 day.

```golang
http {
        proxy_read_timeout 1d;
        proxy_connect_timeout 1d;
        proxy_send_timeout 1d;
        send_timeout 1d;
        ...
}
```

Please check now.
